name: 3.13_ServerlessSecretMgmt
run-name: ${{ github.actor }} is deploying a serverless platform with Secret Management

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'package-lock.json'
      - 'yarn.lock'
      - 'pnpm-lock.yaml'
      - '.snyk'
      - 'snyk/**'
  workflow_dispatch:

jobs:
  predeploy:
    if: ${{ !contains(github.actor, 'snyk') }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job is automatically triggered by a ${{ github.event_name }} event. Actor: ${{ github.actor }}"

  install-dependencies:
    if: ${{ !contains(github.actor, 'snyk') }}
    runs-on: ubuntu-latest
    needs: predeploy
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci

  unit-testing:
    if: ${{ !contains(github.actor, 'snyk') }}
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: npm test

  get-secret:
    if: ${{ !contains(github.actor, 'snyk') }}
    runs-on: ubuntu-latest
    needs: unit-testing
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: aws cli show Secret
        run: |
          aws secretsmanager get-secret-value --secret-id POHLENG-SECRET
      - name: aws cli show SSM
        run: |
          aws ssm get-parameter --name pohleng-parameter

  deploy:
    if: ${{ !contains(github.actor, 'snyk') }}
    name: deploy
    runs-on: ubuntu-latest
    needs: get-secret
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm ci
      - name: serverless deploy
        uses: serverless/github-action@v3.2
        with:
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}